name: lint

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Eslint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '19.7'
      - name: Lint
        run: |
          cd backend
          npm ci --legacy-peer-deps
          npm run lint
          cd ../frontend
          npm ci --legacy-peer-deps
          npm run lint
